name: Docker Website Image CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Docker build
    runs-on: ubuntu-latest
    steps:
    - name: Check out the repo
      uses: actions/checkout@v3
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build website image
      run: | 
        docker build --platform linux --tag aminespinoza/coffeeshop:latest -f src/Dockerfile .
    - name: Publish website image
      run: |
        docker push aminespinoza/coffeeshop:latest
  deploy:
    name: Web App deploy
    needs:
      - build
    runs-on: ubuntu-latest
    steps:
    - name: App service deploy
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'aminescoffeshop'
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        images: 'aminespinoza/coffeeshop:latest'
