name: Infrastructure Deployment

on:
  push:
    branches: [ "iac" ]
  pull_request:
    branches: [ "iac" ]

jobs:
  build:
    name: Terraform settings
    runs-on: ubuntu-latest
    steps:
    - name: Check out the repo
      uses: actions/checkout@v3 
    - name: Terraform version
      run: terraform version
