name: Infrastructure Deployment

on:
  push:
    branches: [ "main" ]
    paths:
      - 'infrastructure/**'

jobs:
  build:
    name: Terraform settings
    runs-on: ubuntu-latest
    steps:
    - name: Check out the repo
      uses: actions/checkout@v3 
    - name: Terraform init
      run: terraform init -backend-config="sas_token=${{ secrets.SAS_TOKEN }}" \
                          -backend-config="storage_account_name=${{ secrets.STORAGE_ACCOUNT_NAME }}" \
                          -backend-config="container_name=${{ secrets.CONTAINER_NAME }}" \
                          -backend-config="key=${{ secrets.KEY }}"
      working-directory: ./infrastructure

    - name: Terraform validate
      run: terraform validate
      working-directory: ./infrastructure
      
    - name: Terraform plan
      run: terraform plan -var-file terraform.tfvars -out=plan.out
      working-directory: ./infrastructure

    - name: Terraform apply
      run: terraform apply -out plan.out
      working-directory: ./infrastructure
